import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/layouts/Navbar";
import Footer from "@/Components/layouts/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// title:{
//     default:"Hero Kidz",
//     template:"%s | Hero Kidz"
//   },
//   description: "Generated by create next app",


export const metadata = {
  metadataBase: new URL("https://hero-kidz-i36h1sgye-mehedi67719s-projects.vercel.app"),

  title: {
    default: "Hero Kidz - Fun & Educational Toys for Kids",
    template: "%s | Hero Kidz"
  },

  description:
    "Hero Kidz is an online kids store offering fun, creative and educational toys for children. Discover amazing toys and learning products for kids.",

  keywords: [
    "kids toys",
    "educational toys",
    "kids store",
    "children toys",
    "Hero Kidz",
    "kids learning toys",
    "kids online shop"
  ],

  authors: [
    {
      name: "Mehedi Hassan",
      url: "https://mehedihassanjashore.netlify.app"
    }
  ],

  creator: "Mehedi Hassan",
  publisher: "Hero Kidz",

  robots: {
    index: true,
    follow: true
  },

  alternates: {
    canonical: "/"
  },

  openGraph: {
    title: "Hero Kidz - Fun & Educational Toys for Kids",
    description:
      "Explore Hero Kidz for creative, safe and educational toys designed for kids.",

    url: "https://hero-kidz-i36h1sgye-mehedi67719s-projects.vercel.app",

    siteName: "Hero Kidz",

    images: [
      {
        url: "/hero-kidz-home.png", // home page screenshot
        width: 1200,
        height: 630,
        alt: "Hero Kidz Kids Toy Store"
      }
    ],

    locale: "en_US",
    type: "website"
  },

  twitter: {
    card: "summary_large_image",
    title: "Hero Kidz - Kids Toy Store",
    description:
      "Discover fun and educational toys for kids at Hero Kidz.",

    images: ["/hero-kidz-home.png"]
  },

  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/logo.png"
  },

  category: "ecommerce"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >

        <header >
          <Navbar />
        </header>

        <main className="md:w-11/12 mx-auto min-h-[calc(100vh-320px)]">
          {children}
        </main>

        <footer >
          <Footer />
        </footer>

      </body>
    </html>
  );
}
